In [1]:
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

pd.options.display.max_columns = None

# Data Paths
BASE_PATH = Path("../../../data/aggregates")


def load_aggregates(base_path: Path):
    # Loading the three pillars of SkillCorner data
    physical = pd.read_csv(base_path / "aus1league_physicalaggregates_20242025.csv")
    obr = pd.read_csv(base_path / "aus1league_obraggregates_20242025.csv")
    passing = pd.read_csv(base_path / "aus1league_passingaggregates_20242025.csv")

    return physical, obr, passing


df_physical, df_obr, df_passing = load_aggregates(BASE_PATH)
print(
    f"Loaded {len(df_physical)} physical entries, {len(df_obr)} OBR entries, and {len(df_passing)} passing entries.",
)

Loaded 406 physical entries, 407 OBR entries, and 407 passing entries.

In [7]:
print(
    "Shapes\n"
    f"\tPhysical Aggregates: {df_physical.shape}\n"
    f"\tOff Ball Runs(OBR) Aggregates: {df_obr.shape}\n"
    f"\tPassing Aggregates: {df_passing.shape}",
)

Shapes
	Physical Aggregates: (406, 65)
	Off Ball Runs(OBR) Aggregates: (407, 130)
	Passing Aggregates: (407, 48)

In [ ]:
df_passing.head()

,competition_edition_id,competition_id,competition_name,season_id,season_name,player_id,player_name,player_short_name,player_birthdate,team_id,team_name,position_group,minutes,minutes_tip,minutes_otip,performance_count,performance_included_count,performance_failed_count,passopportunity_count_total,passopportunity_count_p30tip,pass_count_goalwithin10s_p30tip,pass_count_shotwithin10s_p30tip,pass_count_attempted_total,pass_count_attempted_p30tip,pass_count_completed_p30tip,pass_pct_completed,pass_avgxpass_attempted,pass_avgdistance,pass_count_longrange_attempted_p30tip,pass_count_onetouch_attempted_p30tip,pass_count_quickpass_attempted_p30tip,pass_count_onetouch_dangerous_attempted_p30tip,pass_count_quickpass_dangerous_attempted_p30tip,passopportunity_count_linebreak_p30tip,pass_count_linebreak_attempted_p30tip,pass_count_linebreak_completed_p30tip,passopportunity_count_torun_p30tip,pass_count_torun_attempted_p30tip,pass_count_torun_completed_p30tip,pass_pct_torun_completed,pass_avgxpass_torun_attempted,pass_count_torun_shotwithin10s_p30tip,pass_count_torun_goalwithin10s_p30tip,passopportunity_count_dangerous_p30tip,pass_count_dangerous_attempted_p30tip,pass_pct_dangerous_completed,pass_count_dangerous_completed_p30tip,pass_count_difficultpass_attempted_p30tip
0,870,61,AUS - A-League,95,2024/2025,211,Adam Taggart,A. Taggart,1993-06-02,871,Perth Glory Football Club,Center Forward,97.47,22.83,32.10,13,13,0,524.0,52.96,0.30,1.82,198.0,20.01,15.16,75.76,74.46,12.89,0.61,10.81,3.13,2.83,0.81,1.41,0.61,0.20,23.24,8.89,6.27,70.46,70.66,1.11,0.20,21.12,5.66,57.14,3.23,5.15
1,870,61,AUS - A-League,95,2024/2025,218,Adama Traoré,A. Traoré,1990-02-03,868,Melbourne Victory Football Club,Full Back,89.00,26.23,19.77,2,2,0,296.0,169.30,0.00,2.29,100.0,57.20,50.91,89.00,85.80,16.03,2.86,7.44,14.87,0.57,0.00,42.90,9.15,8.01,37.75,14.87,13.16,88.46,70.43,2.29,0.00,12.58,5.72,60.00,3.43,10.87
2,870,61,AUS - A-League,95,2024/2025,2759,Dino Arslanagić,D. Arslanagić,1993-04-24,1804,Macarthur FC,Central Defender,96.57,27.05,28.14,7,7,0,949.0,150.37,0.16,0.32,378.0,59.90,54.51,91.00,93.09,19.21,4.12,15.53,15.37,0.00,0.16,43.10,11.41,8.71,14.10,6.50,5.86,90.24,89.49,0.00,0.00,0.95,0.32,50.00,0.16,4.60
3,870,61,AUS - A-League,95,2024/2025,2858,Douglas Costa de Souza,Douglas Costa,1990-09-14,869,Sydney Football Club,Center Forward,92.87,28.20,24.48,4,3,1,507.0,179.77,0.35,7.45,143.0,50.70,40.78,80.42,77.00,13.92,1.77,14.54,6.74,1.77,1.42,21.63,7.80,6.03,37.94,15.60,12.41,79.55,72.08,3.19,0.35,42.55,11.35,62.50,7.09,13.83
4,870,61,AUS - A-League,95,2024/2025,2858,Douglas Costa de Souza,Douglas Costa,1990-09-14,869,Sydney Football Club,Midfield,67.56,20.57,17.91,1,1,0,129.0,188.14,1.46,7.29,41.0,59.80,49.59,82.93,78.80,16.89,5.83,18.96,7.29,0.00,1.46,21.88,10.21,8.75,42.29,20.42,17.50,85.71,79.65,4.38,0.00,26.25,8.75,100.00,8.75,13.13

In [ ]:
df_obr.head()

,competition_edition_id,competition_id,competition_name,season_id,season_name,player_id,player_name,player_short_name,player_birthdate,team_id,team_name,position_group,minutes,minutes_tip,minutes_otip,performance_count,performance_included_count,performance_failed_count,offballrun_count_total,offballrun_count_p30tip,behindrun_count_p30tip,comingshortrun_count_p30tip,crossreceiverrun_count_p30tip,droppingoffrun_count_p30tip,overlaprun_count_p30tip,pullinghalfspacerun_count_p30tip,pullingwiderun_count_p30tip,aheadoftheballrun_count_p30tip,supportrun_count_p30tip,underlaprun_count_p30tip,offballrun_count_shotwithin10s_p30tip,behindrun_count_shotwithin10s_p30tip,comingshortrun_count_shotwithin10s_p30tip,crossreceiverrun_count_shotwithin10s_p30tip,droppingoffrun_count_shotwithin10s_p30tip,overlaprun_count_shotwithin10s_p30tip,pullinghalfspacerun_count_shotwithin10s_p30tip,pullingwiderun_count_shotwithin10s_p30tip,aheadoftheballrun_count_shotwithin10s_p30tip,supportrun_count_shotwithin10s_p30tip,underlaprun_count_shotwithin10s_p30tip,offballrun_count_goalwithin10s_p30tip,behindrun_count_goalwithin10s_p30tip,comingshortrun_count_goalwithin10s_p30tip,crossreceiverrun_count_goalwithin10s_p30tip,droppingoffrun_count_goalwithin10s_p30tip,overlaprun_count_goalwithin10s_p30tip,pullinghalfspacerun_count_goalwithin10s_p30tip,pullingwiderun_count_goalwithin10s_p30tip,aheadoftheballrun_count_goalwithin10s_p30tip,supportrun_count_goalwithin10s_p30tip,underlaprun_count_goalwithin10s_p30tip,offballrun_count_targeted_p30tip,behindrun_count_targeted_p30tip,comingshortrun_count_targeted_p30tip,crossreceiverrun_count_targeted_p30tip,droppingoffrun_count_targeted_p30tip,overlaprun_count_targeted_p30tip,pullinghalfspacerun_count_targeted_p30tip,pullingwiderun_count_targeted_p30tip,aheadoftheballrun_count_targeted_p30tip,supportrun_count_targeted_p30tip,underlaprun_count_targeted_p30tip,offballrun_count_received_p30tip,behindrun_count_received_p30tip,comingshortrun_count_received_p30tip,crossreceiverrun_count_received_p30tip,droppingoffrun_count_received_p30tip,overlaprun_count_received_p30tip,pullinghalfspacerun_count_received_p30tip,pullingwiderun_count_received_p30tip,aheadoftheballrun_count_received_p30tip,supportrun_count_received_p30tip,underlaprun_count_received_p30tip,offballrun_avgdistance,behindrun_avgdistance,comingshortrun_avgdistance,crossreceiverrun_avgdistance,droppingoffrun_avgdistance,overlaprun_avgdistance,pullinghalfspacerun_avgdistance,pullingwiderun_avgdistance,aheadoftheballrun_avgdistance,supportrun_avgdistance,underlaprun_avgdistance,offballrun_count_abovehsr_p30tip,behindrun_count_abovehsr_p30tip,comingshortrun_count_abovehsr_p30tip,crossreceiverrun_count_abovehsr_p30tip,droppingoffrun_count_abovehsr_p30tip,overlaprun_count_abovehsr_p30tip,pullinghalfspacerun_count_abovehsr_p30tip,pullingwiderun_count_abovehsr_p30tip,aheadoftheballrun_count_abovehsr_p30tip,supportrun_count_abovehsr_p30tip,underlaprun_count_abovehsr_p30tip,offballrun_count_penaltyarea_p30tip,offballrun_count_dangerous_p30tip,behindrun_count_dangerous_p30tip,comingshortrun_count_dangerous_p30tip,crossreceiverrun_count_dangerous_p30tip,droppingoffrun_count_dangerous_p30tip,overlaprun_count_dangerous_p30tip,pullinghalfspacerun_count_dangerous_p30tip,pullingwiderun_count_dangerous_p30tip,aheadoftheballrun_count_dangerous_p30tip,supportrun_count_dangerous_p30tip,underlaprun_count_dangerous_p30tip,offballrun_count_dangerous_targeted_p30tip,behindrun_count_dangerous_targeted_p30tip,comingshortrun_count_dangerous_targeted_p30tip,crossreceiverrun_count_dangerous_targeted_p30tip,droppingoffrun_count_dangerous_targeted_p30tip,overlaprun_count_dangerous_targeted_p30tip,pullinghalfspacerun_count_dangerous_targeted_p30tip,pullingwiderun_count_dangerous_targeted_p30tip,aheadoftheballrun_count_dangerous_targeted_p30tip,supportrun_count_dangerous_targeted_p30tip,underlaprun_count_dangerous_targeted_p30tip,offballrun_count_dangerous_received_p30tip,behindrun_count_dangerous_received_p30tip,comingshortrun_count_dangerous_received_p30tip,crossreceiverrun_count_dangerous_received_p30tip,droppingoffrun_count_dangerous_received_p30tip,overlaprun_count_dangerous_received_p30tip,pullinghalfspacerun_count_dangerous_received_p30tip,pullingwiderun_count_dangerous_received_p30tip,aheadoftheballrun_count_dangerous_received_p30tip,supportrun_count_dangerous_received_p30tip,underlaprun_count_dangerous_received_p30tip
0,870,61,AUS - A-League,95,2024/2025,211,Adam Taggart,A. Taggart,1993-06-02,871,Perth Glory Football Club,Center Forward,97.47,22.83,32.10,13,13,0,354.0,35.78,9.60,1.31,8.69,0.00,0.71,0.91,0.51,11.22,2.73,0.10,2.83,0.81,0.00,0.71,0.00,0.20,0.0,0.00,0.81,0.30,0.0,0.3,0.1,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.46,4.75,0.71,3.84,0.00,0.51,0.40,0.40,3.94,0.91,0.00,7.18,2.12,0.40,1.11,0.00,0.40,0.10,0.30,2.02,0.71,0.00,13.72,15.39,7.80,15.50,NaN,10.45,7.68,11.39,12.14,14.33,27.10,11.62,4.85,0.2,3.34,0.00,0.30,0.1,0.00,2.12,0.61,0.10,8.99,25.27,8.09,0.1,8.59,0.0,0.10,0.0,0.0,6.77,1.52,0.10,10.01,3.54,0.0,3.84,0.0,0.0,0.0,0.0,2.02,0.61,0.0,4.35,1.62,0.0,1.11,0.0,0.0,0.0,0.0,1.21,0.40,0.0
1,870,61,AUS - A-League,95,2024/2025,218,Adama Traoré,A. Traoré,1990-02-03,868,Melbourne Victory Football Club,Full Back,89.00,26.23,19.77,2,2,0,27.0,15.44,0.00,0.00,1.72,2.29,2.29,0.00,1.14,4.00,4.00,0.00,1.14,0.00,0.00,0.00,0.00,1.14,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.86,0.00,0.00,0.57,1.14,1.72,0.00,0.57,1.14,1.72,0.00,6.29,0.00,0.00,0.57,1.14,1.14,0.00,0.57,1.14,1.72,0.00,12.53,NaN,NaN,25.10,8.94,10.95,NaN,8.68,14.44,9.28,NaN,3.43,0.00,0.0,1.14,0.00,0.57,0.0,0.00,1.14,0.57,0.00,1.72,4.00,0.00,0.0,1.72,0.0,0.57,0.0,0.0,1.14,0.57,0.00,1.14,0.00,0.0,0.57,0.0,0.0,0.0,0.0,0.57,0.00,0.0,1.14,0.00,0.0,0.57,0.0,0.0,0.0,0.0,0.57,0.00,0.0
2,870,61,AUS - A-League,95,2024/2025,2759,Dino Arslanagić,D. Arslanagić,1993-04-24,1804,Macarthur FC,Central Defender,96.57,27.05,28.14,7,7,0,41.0,6.50,0.00,0.48,0.16,4.12,0.00,0.00,0.48,0.79,0.48,0.00,0.16,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.16,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.33,0.00,0.00,0.16,2.38,0.00,0.00,0.32,0.16,0.32,0.00,3.17,0.00,0.00,0.00,2.38,0.00,0.00,0.32,0.16,0.32,0.00,11.86,NaN,14.56,3.22,11.01,NaN,NaN,10.47,20.47,6.46,NaN,0.32,0.00,0.0,0.00,0.16,0.00,0.0,0.00,0.16,0.00,0.00,0.16,0.32,0.00,0.0,0.16,0.0,0.00,0.0,0.0,0.16,0.00,0.00,0.32,0.00,0.0,0.16,0.0,0.0,0.0,0.0,0.16,0.00,0.0,0.16,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.16,0.00,0.0
3,870,61,AUS - A-League,95,2024/2025,2858,Douglas Costa de Souza,Douglas Costa,1990-09-14,869,Sydney Football Club,Center Forward,92.87,28.20,24.48,4,3,1,79.0,28.01,1.06,5.67,1.77,0.00,0.71,2.84,1.77,7.45,5.32,1.42,1.77,0.00,0.35,0.00,0.00,0.00,0.0,0.35,0.00,1.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.28,0.71,2.84,0.71,0.00,0.00,1.42,0.71,1.06,1.77,1.06,8.86,0.71,2.48,0.35,0.00,0.00,1.42,0.71,1.06,1.42,0.71,11.99,12.35,5.85,22.69,NaN,18.80,10.92,9.20,13.12,12.78,16.16,4.25,0.35,0.0,0.71,0.00,0.00,0.0,0.35,1.06,0.71,1.06,2.13,7.45,1.06,0.0,1.42,0.0,0.00,0.0,0.0,2.13,2.48,0.35,2.13,0.71,0.0,0.35,0.0,0.0,0.0,0.0,0.35,0.71,0.0,1.42,0.71,0.0,0.00,0.0,0.0,0.0,0.0,0.35,0.35,0.0
4,870,61,AUS - A-League,95,2024/2025,2858,Douglas Costa de Souza,Douglas Costa,1990-09-14,869,Sydney Football Club,Midfield,67.56,20.57,17.91,1,1,0,22.0,32.09,1.46,5.83,1.46,1.46,0.00,0.00,0.00,14.58,7.29,0.00,2.92,0.00,0.00,0.00,1.46,0.00,0.0,0.00,1.46,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.50,1.46,2.92,0.00,1.46,0.00,0.00,0.00,5.83,5.83,0.00,13.13,0.00,2.92,0.00,1.46,0.00,0.00,0.00,4.38,4.38,0.00,11.53,10.51,9.90,3.89,11.65,NaN,NaN,NaN,7.09,23.43,NaN,2.92,0.00,0.0,0.00,0.00,0.00,0.0,0.00,1.46,1.46,0.00,1.46,5.83,1.46,0.0,1.46,0.0,0.00,0.0,0.0,1.46,1.46,0.00,4.38,1.46,0.0,0.00,0.0,0.0,0.0,0.0,1.46,1.46,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0

In [ ]:
df_physical.head()

,player_name,player_short_name,player_id,player_birthdate,team_name,team_id,competition_name,competition_id,season_name,season_id,position_group,minutes_full_all,minutes_full_tip,minutes_full_otip,count_match,count_match_failed,total_distance_full_all,total_metersperminute_full_all,running_distance_full_all,hsr_distance_full_all,hsr_count_full_all,sprint_distance_full_all,sprint_count_full_all,hi_distance_full_all,hi_count_full_all,medaccel_count_full_all,highaccel_count_full_all,meddecel_count_full_all,highdecel_count_full_all,explacceltohsr_count_full_all,timetohsr_top3,explacceltosprint_count_full_all,timetosprint_top3,psv99,psv99_top5,total_distance_full_tip,total_metersperminute_full_tip,running_distance_full_tip,hsr_distance_full_tip,hsr_count_full_tip,sprint_distance_full_tip,sprint_count_full_tip,hi_distance_full_tip,hi_count_full_tip,medaccel_count_full_tip,highaccel_count_full_tip,meddecel_count_full_tip,highdecel_count_full_tip,explacceltohsr_count_full_tip,explacceltosprint_count_full_tip,total_distance_full_otip,total_metersperminute_full_otip,running_distance_full_otip,hsr_distance_full_otip,hsr_count_full_otip,sprint_distance_full_otip,sprint_count_full_otip,hi_distance_full_otip,hi_count_full_otip,medaccel_count_full_otip,highaccel_count_full_otip,meddecel_count_full_otip,highdecel_count_full_otip,explacceltohsr_count_full_otip,explacceltosprint_count_full_otip
0,Adam Taggart,A. Taggart,211,1993-06-02,Perth Glory Football Club,871,AUS - A-League,61,2024/2025,95,Center Forward,96.78,22.29,32.04,24,0,10515.04,108.64,1413.42,572.67,59.54,184.08,11.00,756.75,70.54,119.38,10.46,99.46,21.67,7.38,0.63,1.25,1.35,28.83,29.98,3087.92,138.53,533.83,288.08,29.71,120.83,6.50,408.92,36.21,43.08,3.42,26.29,5.67,2.50,0.67,4423.04,138.05,755.33,249.38,24.21,48.46,3.00,297.83,27.21,42.38,2.67,38.25,6.96,1.92,0.08
1,Adama Traoré,A. Traoré,218,1990-02-03,Melbourne Victory Football Club,868,AUS - A-League,61,2024/2025,95,Full Back,89.05,26.23,19.99,6,0,9173.67,103.02,1088.83,430.67,43.67,141.33,8.67,572.00,52.33,102.17,5.33,84.17,16.17,3.50,0.72,1.00,1.70,30.07,30.24,3411.67,130.05,478.17,157.00,16.17,60.67,2.83,217.67,19.00,35.50,1.83,26.00,4.00,1.00,0.17,2789.33,139.51,480.17,245.67,21.00,69.67,4.00,315.33,25.00,37.83,2.00,25.67,4.50,1.17,0.50
2,Dino Arslanagić,D. Arslanagić,2759,1993-04-24,Macarthur FC,1804,AUS - A-League,61,2024/2025,95,Central Defender,96.46,28.33,26.86,8,0,9563.50,99.14,1041.12,281.25,23.38,38.25,2.50,319.50,25.88,107.25,3.88,86.12,9.62,3.00,0.80,0.38,NaN,25.82,26.48,3248.62,114.68,320.50,57.38,4.62,6.38,0.12,63.75,4.75,28.62,1.00,24.00,1.88,0.38,0.12,3517.12,130.95,559.00,194.12,15.62,29.12,1.25,223.25,16.88,45.12,1.75,30.75,3.50,1.25,0.00
3,Douglas Costa de Souza,Douglas Costa,2858,1990-09-14,Sydney Football Club,869,AUS - A-League,61,2024/2025,95,Center Forward,94.25,27.43,24.81,4,0,10521.25,111.64,1425.50,406.75,36.00,71.25,4.25,478.00,40.25,91.50,6.50,74.00,10.50,3.25,0.78,0.50,NaN,26.38,26.38,3782.50,137.92,632.75,186.50,16.75,39.25,1.75,225.75,18.50,41.00,2.75,26.50,3.75,1.50,0.00,3652.50,147.23,662.00,199.25,15.50,28.00,2.00,227.25,17.50,28.75,2.00,25.00,3.00,0.75,0.25
4,Douglas Costa de Souza,Douglas Costa,2858,1990-09-14,Sydney Football Club,869,AUS - A-League,61,2024/2025,95,Midfield,67.57,20.63,17.78,1,0,7843.00,116.08,1307.00,318.00,26.00,10.00,2.00,328.00,28.00,67.00,3.00,58.00,7.00,2.00,NaN,0.00,NaN,24.60,24.60,2822.00,136.77,556.00,121.00,9.00,9.00,1.00,130.00,10.00,22.00,1.00,17.00,3.00,1.00,0.00,2840.00,159.70,637.00,169.00,16.00,1.00,0.00,170.00,16.00,26.00,0.00,21.00,2.00,0.00,0.00